version: 2
registries:
  chainguard-npm:
    type: npm-registry
    url: https://libraries.cgr.dev/javascript/
    username: ${{secrets.CG_LIBRARIES_USER}}
    password: ${{secrets.CG_LIBRARIES_PASS}}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - chainguard-npm
    schedule:
      interval: 'daily'
      time: '01:00'
      timezone: 'Asia/Singapore'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'npm'
    directory: '/shared'
    registries:
      - chainguard-npm
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Singapore'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
