pull_request_rules:
  - name: Approve and merge non-major dependabot dependency upgrades
    conditions:
      - author=dependabot[bot]
      - title~=bump [^\s]+ from ([\d]+)\..+ to \1\.
      - check-success~=install
      - check-success~=test-frontend
      - check-success~=test-backend
      - check-success~=test-e2e
      - check-success~=Analyze # CodeQL / Analyze
      - check-success~=CodeQL # CodeQL code scanning results
      - check-success~=GitGuardian
      - check-success~=Semantic Pull Request
      - check-success~=Travis CI - Branch
      - check-success~=coverage/coveralls
      - check-success~=license/snyk
      - check-success~=security/snyk
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
  - name: Approve and merge non-major Snyk.io upgrades
    conditions:
      - author=snyk-bot
      - title~=\[Snyk\] Security upgrade [^\s]+ from ([\d]+)\..+ to \1\.
      - check-success~=install
      - check-success~=test-frontend
      - check-success~=test-backend
      - check-success~=test-e2e
      - check-success~=Analyze # CodeQL / Analyze
      - check-success~=CodeQL # CodeQL code scanning results
      - check-success~=GitGuardian
      - check-success~=Semantic Pull Request
      - check-success~=Travis CI - Branch
      - check-success~=coverage/coveralls
      - check-success~=license/snyk
      - check-success~=security/snyk
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
