# Always validate the PR title, and ignore the commits
# since we only squash commits
titleOnly: true

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  # alias of refactor
  - ref
  - perf
  - test
  - build
  - ci
  - chore
  - revert
