# syntax=docker/dockerfile:1
FROM node:22.22.2-alpine3.22 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
# Install pnpm
RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

FROM base AS build 
# node-modules-builder stage installs/compiles the node_modules folder
# Python version must be specified starting in alpine3.12
RUN apk --no-cache add --virtual native-deps \
    g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python3 git curl \
    build-base cairo-dev pango-dev giflib-dev libjpeg-turbo-dev librsvg-dev && \
    pnpm add -g node-gyp@12.2.0
WORKDIR /build

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/shared/package.json ./packages/shared/
COPY packages/sdk/package.json ./packages/sdk/
COPY apps/frontend/package.json ./apps/frontend/

RUN pnpm install --frozen-lockfile --filter "!services/*" --filter "!packages/react-email-preview/*"

COPY . ./

# These options are only used in the build stage, not the start stage.
ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN pnpm build

ARG APP_VERSION
ARG APP_URL
ARG REPO_URL

# Upload datadog source maps from secret mount, id MUST be `id=dd_api_key` in the docker build command
# Mount creates a file inside /run/secrets/dd_api_key, and source to load the environment variables
# For the content of the mounted file is only accessible in the RUN command where it’s referred in, use && command.
RUN --mount=type=secret,id=dd_api_key \
    export DATADOG_API_KEY=$(cat /run/secrets/dd_api_key) && \
    npx @datadog/datadog-ci sourcemaps upload ./apps/frontend/dist \
    --service=formsg-react \
    --release-version=$APP_VERSION \
    --minified-path-prefix=$APP_URL \
    --repository-url=$REPO_URL

# This stage builds the final container
FROM base
LABEL maintainer=FormSG<form@open.gov.sg>
WORKDIR /opt/formsg


# Copy the built frontend dist for the backend to serve
COPY --from=build /build/apps/frontend/dist /opt/formsg/apps/frontend/dist
# Copy the built formsg-shared package and package.json for the backend to resolve
COPY --from=build /build/packages/shared/package.json /opt/formsg/packages/shared/
COPY --from=build /build/packages/shared/node_modules /opt/formsg/packages/shared/node_modules
COPY --from=build /build/packages/shared/dist /opt/formsg/packages/shared/dist
# Copy the built formsg-sdk package for the backend to resolve
COPY --from=build /build/packages/sdk/package.json /opt/formsg/packages/sdk/
COPY --from=build /build/packages/sdk/node_modules /opt/formsg/packages/sdk/node_modules
COPY --from=build /build/packages/sdk/cjs-entry.cjs /opt/formsg/packages/sdk/
COPY --from=build /build/packages/sdk/dist /opt/formsg/packages/sdk/dist

# Copy required node_modules, package.json scripts and built backend dist for the backend start script to run
COPY --from=build /build/pnpm-workspace.yaml /opt/formsg/pnpm-workspace.yaml
COPY --from=build /build/node_modules /opt/formsg/node_modules
COPY --from=build /build/package.json /opt/formsg/package.json

COPY --from=build /build/apps/backend/node_modules /opt/formsg/apps/backend/node_modules
COPY --from=build /build/apps/backend/package.json /opt/formsg/apps/backend/package.json
COPY --from=build /build/apps/backend/dist /opt/formsg/apps/backend/dist

RUN apk add --no-cache \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    tini \
    cairo \
    pango \
    librsvg \ 
    giflib

# Run as non-privileged user
RUN addgroup -S formsguser && adduser -S -g formsguser formsguser
USER formsguser

ENV NODE_ENV=production
EXPOSE 4545

# tini is the init process that will adopt orphaned zombie processes
# e.g. chromium when launched to create a new PDF
ENTRYPOINT [ "tini", "--" ]
CMD [ "pnpm", "start" ]
