version: '3'
services:
  mockpass:
    image: node:22-slim
    working_dir: /usr/src/mockpass
    command: sh -c "npm install && npm start"
    volumes:
      - ./node_modules/@opengovsg/mockpass:/usr/src/mockpass
    depends_on:
      - backend
    environment:
      - MOCKPASS_NRIC=S6005038D
      - MOCKPASS_UEN=123456789A
      - SHOW_LOGIN_PAGE=true
      - SP_RP_JWKS_ENDPOINT=http://localhost:5000/sp/.well-known/jwks.json
      - CP_RP_JWKS_ENDPOINT=http://localhost:5000/api/v3/corppass/.well-known/jwks.json
    network_mode: "service:backend"
