export const VIRTUAL_LIST_MAX_HEIGHT = 12 * 16
export const VIRTUAL_LIST_OVERSCAN_HEIGHT = 4 * 16
export const VIRTUAL_LIST_ITEM_HEIGHT = 48
export const VIRUTAL_LIST_ITEM_WITH_DESCRIPTION_HEIGHT = 68
