version: '3'
services:
  guardduty-scanner:
    build:
      context: ../../
      dockerfile: serverless/virus-scanner-guardduty/Dockerfile
    expose:
      - '8080'
    ports:
      - '9998:8080'
    env_file: ./.env.development
