version: '3'
services:
  guardduty-scanner:
    build:
      context: ../../
      dockerfile: services/virus-scanner-guardduty/Dockerfile
    expose:
      - '8080'
    ports:
      - '9998:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: ./.env.development
