service: pdf-gen-sparticuz
frameworkVersion: '3' # RATIONALE: Used to avoid authentcation required by serverless v4. 

provider:
  name: aws
  runtime: nodejs20.x # NOTE: Invalid configuration error message occurs but it will still work to deploy node 22. 
  region: ap-southeast-1
  deploymentBucket:
    name: pdf-gen-lambda-code-zip # provisioned by Pulumi in formsg-infra
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::pdf-gen-sparticuz/*"
            - "arn:aws:s3:::pdf-gen-sparticuz"

package:
  artifact: pdf-gen-sparticuz.zip

functions:
  pdf-gen-sparticuz:
    handler: index.handler
    timeout: 300
    memorySize: 2048
