export const sampleFormFields = [
  {
    title: 'This is a Heading',
    description: 'This is a description.',
    required: true,
    disabled: false,
    fieldType: 'section',
  },
  {
    ValidationOptions: {
      selectedValidation: null,
      customVal: null,
    },
    allowPrefill: false,
    lockPrefill: false,
    title: 'Can you hear this Short answer question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'textfield',
  },
  {
    ValidationOptions: {
      selectedValidation: null,
      customVal: null,
    },
    title: 'Can you hear this Long answer question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'textarea',
  },
  {
    fieldOptions: ['Option 1', 'Option 2'],
    othersRadioButton: false,
    title: 'Can you hear this Radio question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'radiobutton',
  },
  {
    ValidationOptions: {
      customMax: null,
      customMin: null,
    },
    fieldOptions: ['Option 1', 'Option 2'],
    othersRadioButton: false,
    validateByValue: false,
    title: 'Can you hear this Checkbox question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'checkbox',
  },
  {
    fieldOptions: ['Option 1', 'Option 2', 'Option 3'],
    title: 'Can you hear this Dropdown question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'dropdown',
  },
  {
    title: 'Can you hear this Yes/No question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'yes_no',
  },
  {
    ratingOptions: {
      steps: 5,
      shape: 'Star',
    },
    title: 'Can you hear this Rating question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'rating',
  },
  {
    autoReplyOptions: {
      hasAutoReply: false,
      autoReplySubject: '',
      autoReplySender: '',
      autoReplyMessage: '',
      includeFormSummary: false,
    },
    isVerifiable: false,
    hasAllowedEmailDomains: false,
    allowedEmailDomains: [],
    title: 'Can you hear this Email question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'email',
  },
  {
    allowIntlNumbers: false,
    isVerifiable: false,
    title: 'Can you hear this Mobile number question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'mobile',
  },
  {
    allowIntlNumbers: false,
    title: 'Can you hear this Home number question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'homeno',
  },
  {
    dateValidation: {
      customMinDate: null,
      customMaxDate: null,
      selectedDateValidation: null,
    },
    invalidDays: [],
    title: 'Can you hear this Date question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'date',
  },
  {
    addMoreRows: false,
    title: 'Can you hear this Table question?',
    description: '',
    required: true,
    disabled: false,
    fieldType: 'table',
    columns: [
      {
        ValidationOptions: {
          customVal: null,
          selectedValidation: null,
        },
        allowPrefill: false,
        lockPrefill: false,
        columnType: 'textfield',
        required: true,
        title: 'Text Field',
      },
    ],
    minimumRows: 2,
    maximumRows: null,
  },
  {
    title: 'Can you hear this Attachment question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'attachment',
    attachmentSize: '1',
  },
  {
    title: 'Can you hear this Number question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'number',
    ValidationOptions: {
      LengthValidationOptions: {
        customVal: null,
        selectedLengthValidation: null,
      },
      RangeValidationOptions: {
        customMin: null,
        customMax: null,
      },
      selectedValidation: null,
    },
  },
  {
    ValidationOptions: {
      customMax: null,
      customMin: null,
    },
    validateByValue: false,
    title: 'Can you hear this Decimal question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'decimal',
  },
  {
    title: 'Can you hear this NRIC question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'nric',
  },
  {
    title: 'Can you hear this UEN question?',
    description: '',
    required: false,
    disabled: false,
    fieldType: 'uen',
  },
]
