import { LandingPayments } from './index'

export const enSG: LandingPayments = {
  onboarding: {
    success: 'An email has been sent to this email address.',
    errors: {
      forbidden:
        'We are unable to send you our guide because your email is not whitelisted on FormSG.',
      general: 'Something went wrong. Please try again later.',
    },
  },
  hero: {
    title: 'Collect payments on your form',
    description:
      'Respondents can now pay for fees and services directly on your form. Enter your agency email to receive our guide on how to get started with payments.',
    emailPlaceholder: 'Enter your email',
    submitButton: 'Submit',
  },
  features: {
    title: 'Payment features',
    selfService: {
      title: 'Self-service',
      description: 'Start collecting payments in just a few simple steps.',
    },
    reconciliation: {
      title: 'Simple reconciliation',
      description:
        'Associate a payment reference ID with every form response ID. Track payments and payouts in one dashboard.',
    },
    trusted: {
      title: 'Trusted payment flows',
      description:
        'We partner with Stripe, a leading payment provider, to ensure a secure and reliable payment experience. Respondents receive notifications from official gov.sg domains. ',
    },
    invoicing: {
      title: 'Invoicing',
      description:
        'Respondents receive an invoice as proof of payment for each completed transaction.',
    },
    paymentMethods: {
      title: 'Multiple payment methods',
      description: 'We support credit card, debit card and PayNow.',
    },
    flexible: {
      title: 'Flexible',
      description:
        "We've got you covered whether you are collecting fixed amounts or varying amounts from respondents.",
    },
  },
  helpCenter: {
    title: 'Help Center',
    description:
      'Have a question? Most answers can be found in our self service Help Center. Common questions include:',
    linkText: 'Visit our Payments Help Center',
    linkToGuide: 'Receive our guide for more information.',
    faq: {
      whatDoINeed: {
        question: 'What do I need to start collecting payments?',
        answer:
          'You would need to create and verify your Stripe account, activate your account and fill in the business onboarding form.',
      },
      transactionFees: {
        question: 'Are there any transaction fees?',
        answer:
          'Stripe, our payment provider, charges transaction fees for every payment. Government agencies can enjoy special transaction rates.',
      },
      invoice: {
        question: 'Is there an invoice or receipt provided?',
        answer:
          'Respondents will receive a receipt generated by Stripe and an invoice generated by FormSG upon successful payment. Invoices will be sent to respondents for payment amounts less than S$1000.',
      },
      reconciliation: {
        question: 'How does reconciliation work?',
        answer:
          'Each payment reference ID is associated with a form response ID. Payment and payout status can be viewed in your form response page as well as on the Stripe dashboard.',
      },
    },
  },
  bottomCta: {
    title: 'Receive our guide to get started on payments',
  },
}
