import {
  BiAlignLeft,
  BiBuilding,
  BiCalculator,
  BiCalendarEvent,
  BiCaretDownSquare,
  BiCloudUpload,
  BiHash,
  BiHeading,
  BiImage,
  BiMailSend,
  BiMobile,
  BiPhone,
  BiRadioCircleMarked,
  BiRename,
  BiSelectMultiple,
  BiStar,
  BiTable,
  BiText,
  BiToggleLeft,
  BiUser,
} from 'react-icons/bi'
import { As } from '@chakra-ui/react'

import { BasicField } from '~shared/types/field'

export const BASICFIELD_TO_READABLE: { [key in BasicField]: string } = {
  [BasicField.Attachment]: 'Attachment',
  [BasicField.Checkbox]: 'Checkbox',
  [BasicField.Date]: 'Date',
  [BasicField.Decimal]: 'Decimal',
  [BasicField.Dropdown]: 'Dropdown',
  [BasicField.Email]: 'Email',
  [BasicField.HomeNo]: 'Home number',
  [BasicField.Image]: 'Image',
  [BasicField.LongText]: 'Long answer',
  [BasicField.Mobile]: 'Mobile number',
  [BasicField.Nric]: 'NRIC',
  [BasicField.Number]: 'Number',
  [BasicField.Radio]: 'Radio',
  [BasicField.Rating]: 'Rating',
  [BasicField.Section]: 'Header',
  [BasicField.ShortText]: 'Short answer',
  [BasicField.Statement]: 'Paragraph',
  [BasicField.Table]: 'Table',
  [BasicField.Uen]: 'UEN',
  [BasicField.YesNo]: 'Yes/No',
}

export const BASICFIELD_TO_ICON: { [key in BasicField]: As } = {
  [BasicField.Attachment]: BiCloudUpload,
  [BasicField.Checkbox]: BiSelectMultiple,
  [BasicField.Date]: BiCalendarEvent,
  [BasicField.Decimal]: BiCalculator,
  [BasicField.Dropdown]: BiCaretDownSquare,
  [BasicField.Email]: BiMailSend,
  [BasicField.HomeNo]: BiPhone,
  [BasicField.Image]: BiImage,
  [BasicField.LongText]: BiAlignLeft,
  [BasicField.Mobile]: BiMobile,
  [BasicField.Nric]: BiUser,
  [BasicField.Number]: BiHash,
  [BasicField.Radio]: BiRadioCircleMarked,
  [BasicField.Rating]: BiStar,
  [BasicField.Section]: BiHeading,
  [BasicField.ShortText]: BiRename,
  [BasicField.Statement]: BiText,
  [BasicField.Table]: BiTable,
  [BasicField.Uen]: BiBuilding,
  [BasicField.YesNo]: BiToggleLeft,
}
