name: AWS Deploy Virus Scanner GuardDuty to IaC OGP AWS environment

on:
  workflow_call:
    inputs:
      checkoutBranch:
        description: 'Branch to checkout code from'
        required: true
        type: string
      gha-environment:
        description: 'GitHub Actions environment'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: string
      provisionedConcurrency:
        description: 'Provisioned concurrency'
        required: true
        type: number
      aws-region:
        description: 'AWS region to use'
        required: false
        default: 'ap-southeast-1'
        type: string
    secrets:
      cicd-role:
        description: 'AWS IAM role to assume by GitHub action runner'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  virus-scanner:
    name: virus scanner guardduty serverless
    runs-on: ubuntu-latest
    environment: ${{ inputs.gha-environment }}
    steps:
      - name: Checkout branch source code into runner environment
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkoutBranch }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Instal pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Grant runner AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.cicd-role }}
          aws-region: ${{ inputs.aws-region }}
      - name: Install node dependencies
        working-directory: ./serverless/virus-scanner-guardduty
        run: pnpm install --frozen-lockfile
      - name: Deploy with Serverless Framework
        working-directory: ./serverless/virus-scanner-guardduty
        env:
          ENV: ${{ inputs.environment }}
          CONCURRENCY: ${{ inputs.provisionedConcurrency }}
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        run: pnpm run deploy
