name: Deploy PDF Generator Lambda to stg-alt3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - stg-alt3

jobs:
  deploy-pdf-gen-lambda:
    name: Deploy PDF Generator Lambda
    uses: ./.github/workflows/deploy-pdf-gen-lambda.yml
    with:
      checkoutBranch: 'stg-alt3'
      gha-environment: 'stg-alt3'
      environment: 'stg-alt3'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
