name: Deploy PDF Generator Lambda to stg

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version tag to deploy (e.g. v7.4.5)'
        required: true
        type: string

jobs:
  deploy-pdf-gen-lambda:
    name: Deploy PDF Generator Lambda
    uses: ./.github/workflows/deploy-pdf-gen-lambda.yml
    with:
      gha-environment: 'stg'
      checkoutBranch: ${{ inputs.version }}
      environment: 'stg'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
