name: Deploy PDF Generator Lambda to stg (main staging environment)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - stg

jobs:
  deploy-pdf-gen-lambda: 
    name: Deploy PDF Generator Lambda
    uses: ./.github/workflows/deploy-pdf-gen-lambda.yml
    with:
      gha-environment: 'stg'
      checkoutBranch: 'stg'
      environment: 'stg'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
