name: Deploy PDF Generator Lambda to production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - release-al2

jobs:
  deploy-pdf-gen-lambda:
    name: Deploy PDF Generator Lambda
    uses: ./.github/workflows/deploy-pdf-gen-lambda.yml
    with:
      checkoutBranch: 'release-al2'
      gha-environment: 'release-al2'
      environment: 'production'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
