name: Deploy Legacy Virus Scanner to new OGP AWS environment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - staging
  # For legacy virus scanner: schedule builds for 12:00AM GMT+8 everyday to get latest ClamAV virus definitions
  schedule:
    - cron: '0 16 * * *'

jobs:
  deploy-scanner:
    name: Deploy Scanner
    uses: ./.github/workflows/aws-deploy-scanner-legacy.yml
    with:
      checkoutBranch: 'staging'
      gha-environment: 'staging'
      environment: 'production'
      provisionedConcurrency: 10
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
