name: Deploy FormSG app to stg-alt3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging-alt3 

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-ecs.yml
    with:
      gha-environment: 'stg-alt3'
      # Environment configuration
      environment: 'stg-alt3'
      environment-site-name: 'stg-alt3'
      shortEnv: 'stg'
      app-version: ${{ github.sha }}
      app-url: 'https://stg-alt3.form.gov.sg'
      react-app-form-sg-sdk-mode: 'staging'

      # AWS configuration
      aws-region: 'ap-southeast-1'

      # ECS configuration
      ecs-cpu: 1024
      ecs-memory: 2048
      ecs-cluster-name: 'formsg-stg-alt3-ecs'
      ecs-service-name: 'formsg-stg-alt3-ecs-service'
      ecs-task-definition: 'formsg-stg-alt3-ecs'
      ecs-task-definition-path: 'deploy/ecs-task-definition.json'
      ecs-container-name: 'formsg-app'

      # CodeDeploy configuration
      codedeploy-application: 'formsg-stg-alt3-ecs-app'
      codedeploy-appspec-path: deploy/appspec.yml
      codedeploy-deployment-group: 'formsg-stg-alt3-ecs-dg'

    secrets:
      # AWS credentials and configuration
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
      ecr-repository: ${{ secrets.ECR_REPO }}
      # Monitoring and analytics configuration
      ga-tracking-id: ${{ secrets.GA_TRACKING_ID }}
      dd-env: ${{ secrets.DD_ENV }}
      dd-rum-app-id: ${{ secrets.DD_RUM_APP_ID }}
      dd-rum-client-token: ${{ secrets.DD_RUM_CLIENT_TOKEN }}
      dd-sample-rate: ${{ secrets.DD_SAMPLE_RATE }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
