name: Deploy Scheduled Closure Lambda to stg-alt3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - stg-alt3

jobs:
  deploy-scheduled-closure-lambda:
    name: Deploy Scheduled Closure Lambda
    uses: ./.github/workflows/deploy-scheduled-closure-lambda.yml
    with:
      gha-environment: 'stg-alt3'
      checkoutBranch: 'stg-alt3'
      environment: 'stg-alt3'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
