name: Deploy to production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - production
  # schedule builds for 12:00AM GMT+8 everyday to get latest virus definitions
  schedule:
    - cron: '0 16 * * *'

jobs:
  deploy-scanner:
    name: Deploy Scanner
    uses: ./.github/workflows/aws-deploy-scanner.yml
    with:
      environment: 'production'
      provisionedConcurrency: 5
    secrets: inherit
