name: Deploy Virus Scanner GuardDuty to new OGP AWS production account

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - uat 

jobs:
  deploy-scanner-guardduty:
    name: Deploy Scanner GuardDuty
    uses: ./.github/workflows/aws-deploy-scanner-guardduty-iac.yml
    with:
      checkoutBranch: uat
      gha-environment: uat
      environment: uat
      provisionedConcurrency: 1
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}