name: Deploy FormSG app to VAPT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - vapt

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-ecs.yml
    with:
      gha-environment: 'vapt'
      # Environment configuration
      environment: 'vapt'
      environment-site-name: 'vapt'
      app-version: ${{ github.sha }}
      app-url: 'https://vapt.form.gov.sg'
      react-app-form-sg-sdk-mode: 'staging'
      # AWS configuration
      aws-region: 'ap-southeast-1'
      ecr-repository: 'formsg'
      # ECS configuration
      ecs-cpu: 1024
      ecs-memory: 2048
      ecs-cluster-name: 'formsg-vapt-ecs'
      ecs-service-name: 'formsg-vapt-ecs-service'
      ecs-task-definition: 'formsg-vapt-ecs'
      ecs-task-definition-path: 'deploy/ecs-task-definition.json'
      ecs-container-name: 'formsg-app'
      # CodeDeploy configuration
      codedeploy-application: 'formsg-vapt-ecs-app'
      codedeploy-appspec-path: deploy/appspec.yml
      codedeploy-deployment-group: 'formsg-vapt-ecs-dg'
      # Datadog config
      dd-env: 'vapt'
    secrets:
      # AWS credentials and configuration
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
      # Monitoring and analytics configuration
      ga-tracking-id: ${{ secrets.GA_TRACKING_ID }}
      dd-rum-app-id: ${{ secrets.DD_RUM_APP_ID }}
      dd-rum-client-token: ${{ secrets.DD_RUM_CLIENT_TOKEN }}
      dd-sample-rate: ${{ secrets.DD_SAMPLE_RATE }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
