name: Deploy Virus Scanner GuardDuty to stg-alt2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - stg-alt2

jobs:
  deploy-scanner-guardduty:
    name: Deploy Scanner GuardDuty
    uses: ./.github/workflows/aws-deploy-scanner-guardduty-iac.yml
    with:
      checkoutBranch: 'stg-alt2'
      gha-environment: 'stg-alt2'
      environment: 'stg-alt2'
      provisionedConcurrency: 1
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
