name: Deploy PDF Generator Lambda to staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - staging

jobs:
  deploy-pdf-gen-lambda: 
    name: Deploy PDF Generator Lambda
    uses: ./.github/workflows/deploy-pdf-gen-lambda.yml
    with:
      gha-environment: 'uat' # Use uat config as this env is not IACed.
      checkoutBranch: 'staging'
      environment: 'staging'
    secrets:
      cicd-role: ${{ secrets.IAC_AWS_CI_ROLE_TO_ASSUME }}
