# Workflow to ensure PR title matches the Conventional Commits spec
# https://www.conventionalcommits.org/en/v1.0.0/
name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            ref
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
