name: Playwright Tests

env:
  NODE_VERSION: '22.22'
  PNPM_VERSION: '10.30.3'

on:
  push:
    branches-ignore:
      - stg
      - stg-alt
      - stg-alt2
      - stg-alt3
      - uat
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - stg
      - stg-alt
      - stg-alt2
      - stg-alt3
      - uat

jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: 1
      DD_TAGS: layer:e2e
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          VITE_APP_FORMSG_SDK_MODE: 'test'
        run: pnpm build:sdk && pnpm --filter formsg-shared --filter formsg-monorepo build
      - name: Cache build artifacts
        uses: actions/cache/save@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: |
            node_modules
            apps/frontend/node_modules
            apps/backend/node_modules
            packages/shared/node_modules
            packages/sdk/node_modules
            apps/frontend/dist
            apps/backend/dist
            packages/shared/dist
            packages/sdk/dist
            services/virus-scanner/build
            services/virus-scanner-guardduty/build
          key: ${{ runner.os }}-build-playwright-${{ github.sha }}
  test:
    needs: setup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          [
            'chromium-login',
            'chromium-encrypt-submission',
            'firefox-login',
            'firefox-encrypt-submission',
          ]
    env:
      AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: 1
      DD_TAGS: layer:e2e
      SHARD_COUNT: 4
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore build artifacts
        uses: actions/cache/restore@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: |
            node_modules
            apps/frontend/node_modules
            apps/backend/node_modules
            packages/shared/node_modules
            packages/sdk/node_modules
            apps/frontend/dist
            apps/backend/dist
            packages/shared/dist
            packages/sdk/dist
            services/virus-scanner/build
            services/virus-scanner-guardduty/build
          key: ${{ runner.os }}-build-playwright-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@7f2b515b64333229315f4701adc590ee6586b270 # v1.0.5
        with:
          languages: js
          service-name: ${{ secrets.DD_SERVICE }}
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
        run: npx playwright test --project=${{ matrix.project }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 30
