name: Playwright Tests
on:
  push:
    branches: 
      - develop
      - release-al2
      - master
  pull_request:
    branches: 
      - develop
      - release-al2
      - master

jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: 1
      DD_TAGS: layer:e2e
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v1.0.5
        with:
          languages: js
          service-name: ${{ secrets.DD_SERVICE }}
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096 -r ${{ env.DD_TRACE_PACKAGE }}
          VITE_APP_FORMSG_SDK_MODE: 'test'
        run: npm run build
      - name: Cache build artifacts
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            frontend/node_modules
            shared/node_modules
            dist
            frontend/dist
            shared/dist
            serverless/virus-scanner/build
            serverless/virus-scanner-guardduty/build
            .next
            frontend/.next
            shared/.next
          key: ${{ runner.os }}-build-${{ github.sha }}
  test:
    needs: setup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          [
            'chromium-login',
            'chromium-email-submission',
            'chromium-encrypt-submission',
            'firefox-login',
            'firefox-email-submission',
            'firefox-encrypt-submission',
          ]
    env:
      AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: 1
      DD_TAGS: layer:e2e
      SHARD_COUNT: 4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore build artifacts
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            frontend/node_modules
            shared/node_modules
            dist
            frontend/dist
            shared/dist
            serverless/virus-scanner/build
            serverless/virus-scanner-guardduty/build
            .next
            frontend/.next
            shared/.next
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v1.0.5
        with:
          languages: js
          service-name: ${{ secrets.DD_SERVICE }}
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
        run: npx playwright test --project=${{ matrix.project }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 30
